frameworkVersion: ">=1.2.1"

service: jannebot

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1
  iamRoleStatements:
  - Effect: Allow
    Action:
      - lambda:InvokeFunction
    Resource: "*"
  environment:
    SLACK_TOKEN: ${file(./config.yml):slack_token}
    SERVERLESS_STAGE: ${opt:stage, self:provider.stage}

functions:
  respond:
    handler: index.respond
    memorySize: 128
    events:
      - http:
          path: respond
          method: post
          cors: true
    package:
      exclude:
        - vendored/**
        - model/**
  gentext:
    handler: handler.genText

package:
  individually: true
  exclude:
    - Dockerfile
    - .git/**
